_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 51
                - 53
                - 55
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 51
                - 53
                - 55
                - 71
                - 98
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.1
            "6": 4.56.0.dev0
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
